#!/bin/bash

## Description: Setup the TYPO3 project
## Usage: setup11
## Example: "ddev setup11"
## ProjectTypes: typo3
## ExecRaw: true

rm -rf var/cache .Build vendor || true
ddev composer install
echo "DROP DATABASE db; CREATE DATABASE db;" | ddev mysql
ddev import-db --file=seeds/db.sql.gz
ddev typo3cms install:setup --skip-integrity-check
ddev import-db --file=seeds/db.sql.gz

ddev typo3cms configuration:set 'BE/debug' 1
ddev typo3cms configuration:set 'FE/debug' 1
ddev typo3cms configuration:set 'SYS/devIPmask' '*'
ddev typo3cms configuration:set 'SYS/displayErrors' 1
ddev typo3cms configuration:set 'SYS/systemLogLevel' 0
ddev typo3cms configuration:set 'SYS/trustedHostsPattern' '.*.*'
ddev typo3cms configuration:set 'MAIL/transport' 'smtp'
ddev typo3cms configuration:set 'MAIL/transport_smtp_server' 'localhost:1025'
ddev typo3cms configuration:set 'GFX/processor' 'ImageMagick'
ddev typo3cms configuration:set 'GFX/processor_path' '/usr/bin/'
ddev typo3cms configuration:set 'GFX/processor_path_lzw' '/usr/bin/'

# ddev typo3 migrations:migrate --no-interaction
ddev typo3cms database:updateschema
ddev typo3cms cache:flush
