#!/bin/bash

VERSION=v11

rm -rf /var/www/html/$VERSION/*

DATABASE_NAME=${VERSION}

mysql -u root -proot -h db -e "DROP DATABASE IF EXISTS $DATABASE_NAME;"

cd /var/www/html/$VERSION/

echo "{}" > composer.json

composer config extra.typo3/cms.web-dir public
composer config repositories.$EXTENSION_KEY path ../../$EXTENSION_KEY
composer config --no-plugins allow-plugins.typo3/cms-composer-installers true
composer config --no-plugins allow-plugins.typo3/class-alias-loader true
composer req typo3/minimal:'^11.5' typo3/cms-felogin:'^11.5' typo3/cms-fluid-styled-content:'^11.5' helhum/typo3-console:'^7.1' jigal/t3adminer:'^11.0' $PACKAGE_NAME:'*@dev' --no-progress -n


cd /var/www/html/$VERSION

TYPO3_INSTALL_DB_DBNAME=$VERSION
./vendor/bin/typo3cms install:setup -n --database-name $DATABASE_NAME
./vendor/bin/typo3cms configuration:set 'BE/debug' 1
./vendor/bin/typo3cms configuration:set 'FE/debug' 1
./vendor/bin/typo3cms configuration:set 'SYS/devIPmask' '*'
./vendor/bin/typo3cms configuration:set 'SYS/displayErrors' 1
./vendor/bin/typo3cms configuration:set 'SYS/systemLogLevel' 0
./vendor/bin/typo3cms configuration:set 'SYS/trustedHostsPattern' '.*.*'
./vendor/bin/typo3cms configuration:set 'MAIL/transport' 'smtp'
./vendor/bin/typo3cms configuration:set 'MAIL/transport_smtp_server' 'localhost:1025'
./vendor/bin/typo3cms configuration:set 'GFX/processor' 'ImageMagick'
./vendor/bin/typo3cms configuration:set 'GFX/processor_path' '/usr/bin/'
./vendor/bin/typo3cms configuration:set 'GFX/processor_path_lzw' '/usr/bin/'

sed -i -e "s/base: ht\//base: \//g" /var/www/html/$VERSION/config/sites/main/config.yaml
sed -i -e 's/base: \/en\//base: \//g' /var/www/html/$VERSION/config/sites/main/config.yaml

./vendor/bin/typo3cms cache:flush
