# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.


---
conf.py:
  copyright: 2020-2021
  project: t3oodle
  version: 0.9
  release: 0.9.1
  latex_documents:
  - - Index
    - t3oodle.tex
    - 't3oodle'
    - Armin Vieweg
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3api:
    - http://docs.typo3.org/typo3cms/CoreApiReference/
    - null
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    t3start:
    - http://docs.typo3.org/typo3cms/GettingStartedTutorial/
    - null
    t3editors:
    - http://docs.typo3.org/typo3cms/EditorsTutorial/
    - null
...
